### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by DeadSix27** [DeadSix27/python_cross_compile_script#18]
- [ ] Auto-detect packages/programs required (e.g gcc,nasm,...)
- [X] ~Update to Qt 5.9 (requires updated patches, don't think any of the sources I got them from have updated yet, e.g Arch packagers)~ Added
- [ ] Make it easier to seperate the package json data (e.g remote hosting)
- [ ] Make force work on lists of products/dependencies

**Comment by hydra3333** [comment]
thumbs up

**Comment by rzcat** [comment]
`make[3]: docbook2x-man: Command not found`
any idea what package provides this command?

**Comment by DeadSix27** [comment]
@rzcat `docbook2x`

A useful thing is to install apt-file (`sudo apt install apt-file`)
Then you can run:
`apt-file search [binary]`

like:
```
$ apt-file search docbook2x-man
docbook2x: /usr/bin/docbook2x-man
docbook2x: /usr/share/man/man1/docbook2x-man.1.gz
```
Which then shows you the package is `docbook2x`

(On debian based linux that is)

**Comment by rzcat** [comment]
@DeadSix27 I did install "docbook2X", however I still dont have that command found. Maybe I dont have a necessary repo? (Fedora 26)
I succeeded compiling ffmpeg using your script before, now I've just installed a brand new Fedora minimal and wanna see what packages are needed

**Comment by DeadSix27** [comment]
@rzcat I'll check later, I'm not sure how to get docbook2x-man on fedora

**Comment by DeadSix27** [comment]
@rzcat Otherwise you could just compile it yourself: http://docbook2x.sourceforge.net/
or maybe you can find out how to **not** build documentation in https://github.com/libexpat/libexpat

I could not find a switch (e.g --disable-doc).. maybe suggest they add it?

**Comment by rzcat** [comment]
@DeadSix27 Never mind,
`ln -s /usr/bin/db2x_docbook2man /usr/bin/docbook2x-man`
solves the problem...
btw, some speed shows as the following
```
[19:37:37][INFO] Downloading libxml2-2.9.5.tar.gz (http://xmlsoft.org/sources/libxml2-2.9.5.tar.gz)
WARNING: Using non-SSL http is not advised..
[|||||||||||||||||||||||||||||||||-----------------] - 3.5MiB/5.2MiB (1.0MiB/s)/s)
```
while the real speed is about 50KB/s as I feel, and I know it should be somewhere around line 656 of your script but I cannot get it correct...😵

**Comment by DeadSix27** [comment]
@rzcat Ye I never got to make the speed function work properly and it fell down in the priority list, because its just a cosmetic.. but feel free to fix it if you can find the issue.

And thanks for figuring that out for fedora, ill add it to the readme :)

**Comment by rzcat** [comment]
@DeadSix27 finally I got ffmpeg compiled again under Fedora 26(minimal), and here are the packages for script to compile ffmpeg:
`wget curl git patch texinfo gettext-devel pax bzip2 gcc-c++ cvs yasm gcc subversion flex m4 bison tar libtool autoconf cmake autogen nettle pkg-config python mercurial docbook2X gperf nasm`
whatsmore, I ran the script before, and the gcc version was 7.1. it seems it wont get updated itself to 7.2 if i re-run the script, is it designed to be like this?

**Comment by DeadSix27** [comment]
@rzcat Ye, it does not update gcc automatically, you'll have to completely rebuild everything. (Intended)

**Comment by rzcat** [comment]
@DeadSix27 is there a switch to check&update gcc automatically everytime i run the script rather than manually delete the whole xcompilers folder?

**Comment by DeadSix27** [comment]
No  and its rather unnecessary because GCC updates are very rare
